/* JAMES WORKFLOW — static, browser-only productivity tracker. */
(() => {
  'use strict';
  const KEY='james-workflow-v2', $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const DEFAULT_SETTINGS={suAht:3.5,nsuAht:1.5,availableMinutes:540,productivityDenominator:472.5,productivityTarget:110,utMinimum:85,storageMode:'localStorage',workingDays:[true,true,true,true,true,false,false]};
  const DEFAULT_ANALYZER={keywords:'',specific:'',noChange:'',capExceptions:''};
  let state={records:[],settings:{...DEFAULT_SETTINGS},holidays:[],theme:'light',analyzerSettings:{...DEFAULT_ANALYZER}}, editing=null;
  const num=v=>{v=Number(v);return Number.isFinite(v)&&v>=0?v:0}; const round=(v,d=2)=>Number.isFinite(v)?+v.toFixed(d):0;
  const pct=v=>`${round(v)}%`, minutes=v=>round(v), hours=v=>round(v/60);
  const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const toast=m=>{
    const x=$('#toast');
    x.textContent=m;
    x.classList.add('show-toast');
    setTimeout(()=>x.classList.remove('show-toast'),2200)
  };

  // STORAGE: localStorage is the reliable static-site default. IndexedDB preference keeps a localStorage mirror fallback.
  function load(){
    try{const x=JSON.parse(localStorage.getItem(KEY));if(x){state={...state,...x,settings:{...DEFAULT_SETTINGS,...x.settings},analyzerSettings:{...DEFAULT_ANALYZER,...x.analyzerSettings}};state.records=state.records.map(calculate)}}
    catch(e){console.warn('Could not load data',e)}}
  function persist(){localStorage.setItem(KEY,JSON.stringify(state)); if(state.settings.storageMode==='indexedDB') idbSave().catch(()=>toast('IndexedDB unavailable; LocalStorage backup kept'));}
  function idbSave(){return new Promise((ok,bad)=>{const r=indexedDB.open('JamesWorkflow',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onerror=()=>bad(r.error);r.onsuccess=()=>{const t=r.result.transaction('data','readwrite');t.objectStore('data').put(state,'main');t.oncomplete=ok;t.onerror=()=>bad(t.error)}})}

  // DATE / WORKING DAYS: weekday indexes follow JS (Sunday=0); configuration UI uses Monday-first.
  const iso=d=>d.toISOString().slice(0,10); const dateObj=s=>new Date(`${s}T00:00:00`);
  function isWorkingDate(s){const d=dateObj(s), mondayIndex=(d.getDay()+6)%7;return !!state.settings.workingDays[mondayIndex]&&!state.holidays.includes(s)}
  function monthDates(month){if(!month)return[];const [y,m]=month.split('-').map(Number), out=[];for(let d=1;d<=new Date(y,m,0).getDate();d++){const v=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;if(isWorkingDate(v))out.push(v)}return out}
  function daysInfo(month){const ds=monthDates(month), today=iso(new Date()), completed=ds.filter(d=>state.records.some(r=>r.date===d)).length;return{total:ds.length,completed,remaining:ds.filter(d=>d>=today&&!state.records.some(r=>r.date===d)).length}}

  // CALCULATIONS: this is the only engine used for preview, saved rows, dashboard, charts and exports.
  function calculate(raw){
    const s=state.settings,
      su=num(raw.su),
      nsu=num(raw.nsu),
      ut=num(raw.ut),
      utEx=num(raw.utException),
      prodEx=num(raw.prodException),
      total=su+nsu, 
      weighted=su*s.suAht+nsu*s.nsuAht, 
      exception=utEx+prodEx;
    // Productivity = weighted work minutes ÷ available minutes × 100. Exception minutes reduce available time.
    const effective540=Math.max(1,s.availableMinutes-prodEx), 
      effective472=Math.max(1,s.productivityDenominator-prodEx), 
      prod540=weighted/effective540*100,
      
      productivity=weighted/effective472*100;
    
    // Excel equivalent: IFERROR(472.5 / (SU% * 3.5 + NSU% * 1.5), "0").
    // These percentage shares stay decimal internally: 50% is 0.50.
    const suPct=total>0 ? su/total : 0,
      nsuPct=total>0 ? nsu/total : 0,
      targetAht=(suPct*s.suAht)+(nsuPct*s.nsuAht),
      targetUrls=targetAht>0 ? 472.5/targetAht : 0,
      deficitUrls=targetUrls-total,
      utDeficit=Math.max(0,s.utMinimum-ut), 
      prodDeficit=Math.max(0,s.productivityTarget-productivity);
    const rem_deficit_540 = 100 - prod540, rem_deficit_472 = 100-productivity;
    return{date:raw.date||'',su,nsu,ut,utException:utEx,prodException:prodEx,total,weighted,suPct:suPct*100,nsuPct:nsuPct*100,targetUrls,deficitUrls,utDeficit,prod540,productivity,rem_deficit_540,rem_deficit_472,prodDeficit,exception,utExceptionHours:hours(utEx),prodExceptionHours:hours(prodEx),exceptionHours:hours(exception)};
  }
  function monthRecords(){const m=$('#monthPicker').value;return state.records.filter(r=>r.date.startsWith(m)).sort((a,b)=>a.date.localeCompare(b))}
  // REQUIRED PERFORMANCE: (target average × working days − achieved total) ÷ remaining working days.
  function required(records,days){
    const avgUT=records.length?records.reduce((a,r)=>a+r.ut,0)/records.length:0, 
      avgProd=records.length?records.reduce((a,r)=>a+r.productivity,0)/records.length:0;
    return{avgUT,avgProd,newUT:days.remaining?Math.max(0,(state.settings.utMinimum*days.total-records.reduce((a,r)=>a+r.ut,0))/days.remaining):0,newProd:days.remaining?Math.max(0,(state.settings.productivityTarget*days.total-records.reduce((a,r)=>a+r.productivity,0))/days.remaining):0}}
  const classFor=(v,target)=>v>=target?'metric-good':'metric-bad';
  // Function For Preview
  function preview(){
    const r=calculate(formRaw()),
      p=$('#preview');
    $('#utDeficitInput').value=round(r.utDeficit);
    p.innerHTML=`
    <div class="preview-list">
    <span>Total URLs</span><b>${round(r.total)}</b>
    <span>SU / NSU</span><b>${pct(r.suPct)} / ${pct(r.nsuPct)}</b>
    <span>Weighted minutes</span><b>${minutes(r.weighted)}</b>
    <span>Target URLs</span><b>${round(r.targetUrls)}</b>
    <span>Deficit URLs</span><b class="${r.deficitUrls<0?'metric-good':'metric-bad'}">${round(r.deficitUrls)}</b>
    <span>UT / deficit</span><b class="${classFor(r.ut,state.settings.utMinimum)}">${pct(r.ut)} / ${pct(r.utDeficit)}</b>
    <span>Productivity @540</span><b class="${classFor(r.prod540,state.settings.productivityTarget)}">${pct(r.prod540)}</b>
    <span>Defict(540)</span><b>${pct(r.rem_deficit_540)}</b>
    <span>Productivity @472.5</span><b class="${classFor(r.productivity,state.settings.productivityTarget)}">${pct(r.productivity)}</b>
    <span>Deficit(472.50)</span><b>${pct(r.rem_deficit_472)}</b>
    <span>Exceptions</span><b>${minutes(r.exception)} min / ${hours(r.exception)} h</b>
    <span>New UT / Productivity</span><b>${pct(r.newUT||0)} / ${pct(r.newProductivity||0)}</b>
    </div>`
  }
  // Preview Ending
  
  function formRaw(){return{date:$('#date').value,su:$('#su').value,nsu:$('#nsu').value,ut:$('#ut').value,utException:$('#utException').value,prodException:$('#prodException').value}}
  function resetForm(){editing=null;$('#entryForm').reset();$('#date').value=iso(new Date());preview()}
  function saveDay(){const raw=formRaw();if(!raw.date)return toast('Please select a date');const r=calculate(raw), index=state.records.findIndex(x=>x.date===r.date);if(index>=0)state.records[index]=r;else state.records.push(r);state.records.sort((a,b)=>a.date.localeCompare(b));persist();resetForm();render();toast(index>=0?'Day updated':'Day saved')}
  function edit(date){const r=state.records.find(x=>x.date===date);if(!r)return;editing=date;['date','su','nsu','ut','utException','prodException'].forEach(k=>$('#'+k).value=r[k]);showPage('entry');preview();window.scrollTo({top:0,behavior:'smooth'})}
  function del(date){if(confirm(`Delete ${date}?`)){state.records=state.records.filter(r=>r.date!==date);persist();render();toast('Record deleted')}}

  function aggregate(records){const n=records.length,sum=k=>records.reduce((a,r)=>a+num(r[k]),0),avg=k=>n?sum(k)/n:0;return{n,total:sum('total'),su:sum('su'),nsu:sum('nsu'),target:sum('targetUrls'),deficit:sum('deficitUrls'),exception:sum('exception'),utEx:sum('utException'),prodEx:sum('prodException'),avgSu:avg('suPct'),avgNsu:avg('nsuPct'),avgUt:avg('ut'),avgProd:avg('productivity')}}
  const card=(label,value,cls='')=>`<div class="kpi"><small>${label}</small><strong class="${cls}">${value}</strong></div>`;
  function renderDashboard(){const rs=monthRecords(), a=aggregate(rs), d=daysInfo($('#monthPicker').value), req=required(rs,d), today=state.records.find(r=>r.date===iso(new Date())); const sections=[['VOLUME',[['Total Count',a.n],['Total SU',a.su],['Total NSU',a.nsu],['Total URLs',a.total],['Total Target URLs',round(a.target)],['Total Deficit URLs',round(a.deficit),a.deficit<0?'metric-good':'metric-bad']]],['AVERAGES',[['Average SU%',pct(a.avgSu)],['Average NSU%',pct(a.avgNsu)],['Average UT',pct(a.avgUt),classFor(a.avgUt,state.settings.utMinimum)],['Average Productivity',pct(a.avgProd),classFor(a.avgProd,state.settings.productivityTarget)]]],['EXCEPTIONS',[['Total Exception',`${minutes(a.exception)} min`],['Total UT Exception',`${minutes(a.utEx)} min`],['Total Productivity Exception',`${minutes(a.prodEx)} min`],['Total Exception Hours',hours(a.exception)],['Total UT Exception Hours',hours(a.utEx)],['Total Productivity Exception Hours',hours(a.prodEx)]]],['WORKING DAYS',[['Total Working Days',d.total],['Working Days Completed',d.completed],['Remaining Working Days',d.remaining]]],['TODAY',[['Today Date',today?today.date:'—'],['Today SU',today?today.su:'—'],['Today NSU',today?today.nsu:'—'],['Today Total',today?today.total:'—'],['Today UT',today?pct(today.ut):'—'],['Today Productivity',today?pct(today.productivity):'—'],["Today's Target URLs",today?round(today.targetUrls):'—'],['Completed URLs',today?today.total:'—'],['Deficit',today?round(today.deficitUrls):'—']]]];$('#dashboardBlocks').innerHTML=sections.map(([t,x])=>`<section class="kpi-section"><h3>${t}</h3><div class="kpis">${x.map(v=>card(...v)).join('')}</div></section>`).join('');$('#achievementBand').innerHTML=card('Current Avg',`${pct(req.avgUT)} UT · ${pct(req.avgProd)} Productivity`)+card('Daily Avg Need',`${pct(req.newUT)} UT · ${pct(req.newProd)} Productivity`)+card('Target to Achieve',`${pct(state.settings.utMinimum)} UT · ${pct(state.settings.productivityTarget)} Productivity`);drawCharts(rs)}
  function filtered(){const q=$('#searchRecords').value.trim(), f=$('#recordFilter').value;return state.records.filter(r=>r.date.includes(q)&&({all:1,utBelow:r.ut<state.settings.utMinimum,utAchieved:r.ut>=state.settings.utMinimum,prodBelow:r.productivity<state.settings.productivityTarget,prodAchieved:r.productivity>=state.settings.productivityTarget,exceptions:r.exception>0}[f])).sort((a,b)=>b.date.localeCompare(a.date))}
  function renderRecords(){const rs=filtered(), d=daysInfo($('#monthPicker').value), req=required(monthRecords(),d);$('#recordCount').textContent=`${rs.length} record${rs.length===1?'':'s'}`;$('#recordsTable tbody').innerHTML=rs.map(r=>`<tr><td>${r.date}</td><td>${isWorkingDate(r.date)?'Working':'Off'}</td><td>${r.su}</td><td>${r.nsu}</td><td>${r.total}</td><td>${pct(r.suPct)}</td><td>${pct(r.nsuPct)}</td><td>${round(r.targetUrls)}</td><td class="${r.deficitUrls<0?'metric-good':'metric-bad'}">${round(r.deficitUrls)}</td><td class="${classFor(r.ut,state.settings.utMinimum)}">${pct(r.ut)}</td><td>${pct(r.utDeficit)}</td><td>${pct(r.prod540)}</td><td class="${classFor(r.productivity,state.settings.productivityTarget)}">${pct(r.productivity)}</td><td>${minutes(r.exception)}</td><td>${minutes(r.utException)}</td><td>${minutes(r.prodException)}</td><td>${pct(req.newUT)}</td><td>${pct(req.newProd)}</td><td class="actions"><button data-edit="${r.date}">Edit</button><button data-delete="${r.date}" class="secondary">Delete</button></td></tr>`).join('')||'<tr><td colspan="21">No records match your filter.</td></tr>';$$('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>del(b.dataset.delete))}
  function renderReport(){const rs=monthRecords(),a=aggregate(rs),d=daysInfo($('#monthPicker').value),q=required(rs,d), max=k=>rs.length?Math.max(...rs.map(r=>r[k])):0,min=k=>rs.length?Math.min(...rs.map(r=>r[k])):0;$('#reportPeriod').textContent=$('#monthPicker').value||'Selected month';const vals=[['Total working days',d.total],['Completed days',d.completed],['Remaining days',d.remaining],['Total SU',a.su],['Total NSU',a.nsu],['Total URLs',a.total],['Average SU%',pct(a.avgSu)],['Average NSU%',pct(a.avgNsu)],['Average UT',pct(a.avgUt)],['Average Productivity',pct(a.avgProd)],['Total Target URLs',round(a.target)],['Total Deficit URLs',round(a.deficit)],['Total exceptions',`${a.exception} min / ${hours(a.exception)} h`],['New UT',pct(q.newUT)],['New Productivity',pct(q.newProd)],['Days below 85% UT',rs.filter(r=>r.ut<state.settings.utMinimum).length],['Days at/above 85% UT',rs.filter(r=>r.ut>=state.settings.utMinimum).length],['Highest UT',pct(max('ut'))],['Lowest UT',pct(min('ut'))],['Highest Productivity',pct(max('productivity'))],['Lowest Productivity',pct(min('productivity'))]];$('#monthlyReport').innerHTML=`<div class="kpis">${vals.map(v=>card(...v)).join('')}</div>`}
  function chart(canvas,records,series){const c=$(canvas),ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=c.clientWidth,H=c.clientHeight;ctx.clearRect(0,0,W,H);if(!records.length){ctx.fillStyle=getComputedStyle(document.body).color;ctx.fillText('No data for this month',16,35);return}const max=Math.max(1,...series.flatMap(s=>records.map(s.get))),pad=28,dx=(W-pad*2)/Math.max(1,records.length-1);series.forEach(s=>{ctx.beginPath();records.forEach((r,i)=>{const x=pad+i*dx,y=H-pad-(s.get(r)/max)*(H-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=s.color;ctx.lineWidth=2;ctx.stroke()});ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.font='11px system-ui';ctx.fillText(`0`,5,H-pad);ctx.fillText(round(max),3,15);series.forEach((s,i)=>{ctx.fillStyle=s.color;ctx.fillRect(W-90,9+i*14,8,8);ctx.fillStyle=getComputedStyle(document.body).color;ctx.fillText(s.name,W-78,17+i*14)})}
  function drawCharts(rs){chart('#utChart',rs,[{name:'UT%',color:'#0f766e',get:r=>r.ut}]);chart('#prodChart',rs,[{name:'Prod%',color:'#7652cb',get:r=>r.productivity}]);chart('#volumeChart',rs,[{name:'SU',color:'#0f766e',get:r=>r.su},{name:'NSU',color:'#e59b32',get:r=>r.nsu}]);chart('#targetChart',rs,[{name:'Target',color:'#7652cb',get:r=>r.targetUrls},{name:'Done',color:'#0f766e',get:r=>r.total}]);chart('#deficitChart',rs,[{name:'Deficit',color:'#c83b4d',get:r=>Math.abs(r.deficitUrls)}]);chart('#exceptionChart',rs,[{name:'Minutes',color:'#e59b32',get:r=>r.exception}])}
  function renderSettings(){const f=$('#settingsForm');Object.entries(state.settings).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});const names=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];$('#weekdayConfig').innerHTML=names.map((n,i)=>`<label>${n}<select data-weekday="${i}"><option value="true" ${state.settings.workingDays[i]?'selected':''}>Working</option><option value="false" ${!state.settings.workingDays[i]?'selected':''}>Off</option></select></label>`).join('');$('#holidayList').innerHTML=state.holidays.sort().map(x=>`<span class="chip">${x}<button data-holiday="${x}" title="Remove">×</button></span>`).join('')||'<span class="muted">No excluded dates.</span>';$$('[data-holiday]').forEach(b=>b.onclick=()=>{state.holidays=state.holidays.filter(x=>x!==b.dataset.holiday);persist();renderSettings();render()})}
  function saveSettings(){const f=$('#settingsForm'),n={};Object.keys(DEFAULT_SETTINGS).forEach(k=>{if(f.elements[k])n[k]=k==='storageMode'?f.elements[k].value:num(f.elements[k].value)});n.workingDays=$$('[data-weekday]').map(x=>x.value==='true');state.settings={...state.settings,...n};persist();preview();render();toast('Settings saved')}
  function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function exportCsv(){const rs=monthRecords(),a=aggregate(rs),heads=['Date','Days','SU','NSU','Total','SU%','NSU%','Target URLs','Deficit URLs','UT%','UT Deficit','Productivity @540','Productivity @472.5','Exception','UT Exception','UT Exception Hours','Productivity Exception','Productivity Exception Hours'];const rows=rs.map(r=>[r.date,isWorkingDate(r.date)?'Working':'Off',r.su,r.nsu,r.total,r.suPct,r.nsuPct,r.targetUrls,r.deficitUrls,r.ut,r.utDeficit,r.prod540,r.productivity,r.exception,r.utException,r.utExceptionHours,r.prodException,r.prodExceptionHours]);const csv=[['JAMES WORKFLOW'],['Selected month',$('#monthPicker').value],[],heads,...rows,[],['SUMMARY'],['Total URLs',a.total],['Average UT',a.avgUt],['Average Productivity',a.avgProd]].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');download(`james-workflow-${$('#monthPicker').value}.csv`,'text/csv;charset=utf-8',csv)}
  function importJson(e){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!Array.isArray(x.records)||!x.settings)throw Error();state={...state,...x,settings:{...DEFAULT_SETTINGS,...x.settings},analyzerSettings:{...DEFAULT_ANALYZER,...x.analyzerSettings}};state.records=state.records.map(calculate);persist();renderSettings();resetForm();render();toast('Backup restored')}catch(_){toast('That file is not a valid JAMES WORKFLOW backup')}};reader.readAsText(f)}
  function showPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#pageTitle').textContent=id==='dashboard'?'JAMES WORKFLOW':`${id[0].toUpperCase()+id.slice(1)} · JAMES WORKFLOW`;if(id==='reports')renderReport()}
  function render(){renderDashboard();renderRecords();renderReport()}
  function init(){load();document.body.classList.toggle('dark',state.theme==='dark');$('#monthPicker').value=iso(new Date()).slice(0,7);resetForm();renderSettings();render();$$('#nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));['su','nsu','ut','utException','prodException','date'].forEach(id=>$('#'+id).addEventListener('input',preview));$('#saveDay').onclick=saveDay;$('#resetForm').onclick=resetForm;$('#searchRecords').oninput=renderRecords;$('#recordFilter').onchange=renderRecords;$('#monthPicker').onchange=render;$('#saveSettings').onclick=saveSettings;$('#addHoliday').onclick=()=>{const d=$('#holidayDate').value;if(d&&!state.holidays.includes(d)){state.holidays.push(d);persist();renderSettings();render()}};$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',state.theme==='dark');persist();render()};$('#exportJson').onclick=()=>download(`james-workflow-backup-${iso(new Date())}.json`,'application/json',JSON.stringify(state,null,2));$('#importJson').onchange=importJson;$('#exportCsv').onclick=exportCsv;$('#printBtn').onclick=$('#dataPrint').onclick=$('#pdfBtn').onclick=()=>{showPage('reports');setTimeout(()=>window.print(),50)};initAnalyzer();$('#clearData').onclick=()=>{if(confirm('Clear all records and excluded dates? This cannot be undone.')){state.records=[];state.holidays=[];persist();renderSettings();render();toast('All data cleared')}};window.addEventListener('resize',()=>{drawCharts(monthRecords());drawPies(aggregate(monthRecords()))})}
  function aggregate(records){const n=records.length,sum=k=>records.reduce((a,r)=>a+num(r[k]),0),avg=k=>n?sum(k)/n:0,su=sum('su'),nsu=sum('nsu'),total=su+nsu,target=sum('targetUrls');return{n,su,nsu,total,target,completed:total,deficit:target-total,ut:sum('ut'),utDeficit:sum('utDeficit'),exception:sum('exception'),utEx:sum('utException'),prodEx:sum('prodException'),avgSu:total?su/total*100:0,avgNsu:total?nsu/total*100:0,avgUt:avg('ut'),avgProd540:avg('prod540'),avgProd:avg('productivity')}}
  const deficitText=a=>a.deficit<0?'Exceeded by '+round(Math.abs(a.deficit)):'Deficit '+round(a.deficit);
  const summaryValues=a=>[['Total SU',a.su],['Total NSU',a.nsu],['Total URLs',a.total],['Total Target URLs',round(a.target)],['Total Completed URLs',a.completed],['Total Target/URL Deficit',deficitText(a),a.deficit<0?'metric-good':'metric-bad'],['Total UT Minutes',round(a.ut)],['Total UT Deficit',round(a.utDeficit)],['Total Exception Minutes',minutes(a.exception)],['Total UT Exception Minutes',minutes(a.utEx)],['Total Productivity Exception Minutes',minutes(a.prodEx)],['Average SU%',pct(a.avgSu)],['Average NSU%',pct(a.avgNsu)],['Average UT%',pct(a.avgUt)],['Average Productivity @540',pct(a.avgProd540)],['Average Productivity @472.50',pct(a.avgProd)],['Average Productivity with Exception',pct(a.avgProd)]];
  function renderRecords(){const rs=filtered(),all=monthRecords(),a=aggregate(all),d=daysInfo($('#monthPicker').value),req=required(all,d);$('#recordCount').textContent=rs.length+' record'+(rs.length===1?'':'s')+' · '+all.length+' in selected month';$('#recordsTable tbody').innerHTML=rs.map(r=>'<tr><td>'+r.date+'</td><td>'+(isWorkingDate(r.date)?'Working':'Off')+'</td><td>'+r.su+'</td><td>'+r.nsu+'</td><td>'+r.total+'</td><td>'+pct(r.suPct)+'</td><td>'+pct(r.nsuPct)+'</td><td>'+round(r.targetUrls)+'</td><td class="'+(r.deficitUrls<0?'metric-good':'metric-bad')+'">'+(r.deficitUrls<0?'Exceeded '+round(Math.abs(r.deficitUrls)):round(r.deficitUrls))+'</td><td>'+pct(r.ut)+'</td><td>'+pct(r.utDeficit)+'</td><td>'+pct(r.prod540)+'</td><td>'+pct(r.productivity)+'</td><td>'+minutes(r.exception)+'</td><td>'+minutes(r.utException)+'</td><td>'+r.utExceptionHours+'</td><td>'+minutes(r.prodException)+'</td><td>'+r.prodExceptionHours+'</td><td>'+pct(req.newUT)+'</td><td>'+pct(req.newProd)+'</td><td class="actions"><button data-edit="'+r.date+'">Edit</button><button data-delete="'+r.date+'" class="secondary">Delete</button></td></tr>').join('')||'<tr><td colspan="21">No records match your filter.</td></tr>';$('#recordsSummary').innerHTML='<tr class="cumulative-row"><th colspan="2">CUMULATIVE SUMMARY</th><td>'+a.su+'</td><td>'+a.nsu+'</td><td>'+a.total+'</td><td>'+pct(a.avgSu)+'</td><td>'+pct(a.avgNsu)+'</td><td>'+round(a.target)+'</td><td class="'+(a.deficit<0?'metric-good':'metric-bad')+'">'+deficitText(a)+'</td><td>'+pct(a.avgUt)+'</td><td>'+round(a.utDeficit)+'</td><td>'+pct(a.avgProd540)+'</td><td>'+pct(a.avgProd)+'</td><td>'+minutes(a.exception)+'</td><td>'+minutes(a.utEx)+'</td><td>—</td><td>'+minutes(a.prodEx)+'</td><td>—</td><td>—</td><td>—</td><td>'+a.n+' days</td></tr>';$$('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>del(b.dataset.delete))}
  function renderReport(){const rs=monthRecords(),a=aggregate(rs),d=daysInfo($('#monthPicker').value),q=required(rs,d);$('#reportPeriod').textContent=$('#monthPicker').value||'Selected month';const vals=[['Total working days',d.total],['Completed days',d.completed],['Remaining days',d.remaining],...summaryValues(a),['New UT',pct(q.newUT)],['New Productivity',pct(q.newProd)]];$('#monthlyReport').innerHTML='<div class="kpis">'+vals.map(v=>card(...v)).join('')+'</div>';$('#reportSummary').innerHTML='<div class="kpis">'+summaryValues(a).map(v=>card(...v)).join('')+'</div>';drawPies(a)}
  function renderDashboard(){const rs=monthRecords(),a=aggregate(rs),d=daysInfo($('#monthPicker').value),req=required(rs,d);$('#dashboardBlocks').innerHTML='<section class="kpi-section"><h3>CUMULATIVE SUMMARY</h3><div class="kpis">'+summaryValues(a).map(v=>card(...v)).join('')+'</div></section><section class="kpi-section"><h3>WORKING DAYS</h3><div class="kpis">'+card('Total Working Days',d.total)+card('Working Days Completed',d.completed)+card('Remaining Working Days',d.remaining)+'</div></section>';$('#achievementBand').innerHTML=card('Current Avg',pct(req.avgUT)+' UT · '+pct(req.avgProd)+' Productivity')+card('Daily Avg Need',pct(req.newUT)+' UT · '+pct(req.newProd)+' Productivity')+card('Target to Achieve',pct(state.settings.utMinimum)+' UT · '+pct(state.settings.productivityTarget)+' Productivity');drawCharts(rs)}
  function canvasSetup(sel){const c=$(sel);if(!c)return;const ctx=c.getContext('2d'),W=c.clientWidth||300,H=c.clientHeight||205,d=devicePixelRatio||1;c.width=W*d;c.height=H*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,W,H);return{c,ctx,W,H}}
  function chartTip(c,hits){c.onmousemove=e=>{const r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,q=hits.find(v=>x>=v.x&&x<=v.x+v.w&&y>=v.y&&y<=v.y+v.h);let t=$('#chartTip');if(!t){t=document.createElement('div');t.id='chartTip';t.className='chart-tip';document.body.append(t)}if(q){t.textContent=q.label+': '+round(q.value);t.style.left=e.clientX+12+'px';t.style.top=e.clientY+12+'px';t.hidden=false}else t.hidden=true};c.onmouseleave=()=>{const t=$('#chartTip');if(t)t.hidden=true}}
  function barChart(sel,records,series){const z=canvasSetup(sel);if(!z)return;const{c,ctx,W,H}=z,p=34,hits=[];if(!records.length){ctx.fillStyle=getComputedStyle(document.body).color;ctx.fillText('No data for this month',16,35);return}const max=Math.max(1,...series.flatMap(x=>records.map(x.get))),gw=(W-p*2)/records.length,bw=Math.max(3,gw/(series.length+1));series.forEach((x,j)=>records.forEach((r,i)=>{const v=x.get(r),h=v/max*(H-p*2),bx=p+i*gw+j*bw,by=H-p-h;ctx.fillStyle=x.color;ctx.fillRect(bx,by,bw-2,h);hits.push({x:bx,y:by,w:bw,h,label:r.date+' · '+x.name,value:v})}));ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.fillText('0',8,H-p);ctx.fillText(round(max),4,15);series.forEach((x,i)=>{ctx.fillStyle=x.color;ctx.fillRect(W-105,8+i*14,9,9);ctx.fillStyle=getComputedStyle(document.body).color;ctx.fillText(x.name,W-92,17+i*14)});chartTip(c,hits)}
  function pieChart(sel,parts){const z=canvasSetup(sel);if(!z)return;const{c,ctx,W,H}=z,total=parts.reduce((x,p)=>x+p.value,0),cx=W*.35,cy=H*.52,r=Math.min(W,H)*.27;if(!total){ctx.fillStyle=getComputedStyle(document.body).color;ctx.fillText('No data for this month',16,35);return}let a=-Math.PI/2,arcs=[];parts.forEach(p=>{const span=p.value/total*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,a+span);ctx.closePath();ctx.fillStyle=p.color;ctx.fill();arcs.push({start:a,end:a+span,label:p.name,value:p.value});a+=span});parts.forEach((p,i)=>{ctx.fillStyle=p.color;ctx.fillRect(W*.67,24+i*23,10,10);ctx.fillStyle=getComputedStyle(document.body).color;ctx.fillText(p.name+' ('+round(p.value)+')',W*.67+15,33+i*23)});c.onmousemove=e=>{const box=c.getBoundingClientRect(),dx=e.clientX-box.left-cx,dy=e.clientY-box.top-cy,dist=Math.hypot(dx,dy),ang=Math.atan2(dy,dx);let q=dist<=r&&arcs.find(v=>ang>=v.start&&ang<=v.end);let t=$('#chartTip');if(!t){t=document.createElement('div');t.id='chartTip';t.className='chart-tip';document.body.append(t)}if(q){t.textContent=q.label+': '+round(q.value);t.style.left=e.clientX+12+'px';t.style.top=e.clientY+12+'px';t.hidden=false}else t.hidden=true};c.onmouseleave=()=>{const t=$('#chartTip');if(t)t.hidden=true}}
  function drawCharts(rs){const running=rs.map((_,i)=>aggregate(rs.slice(0,i+1)));barChart('#volumeChart',rs,[{name:'SU',color:'#0f766e',get:r=>r.su},{name:'NSU',color:'#e59b32',get:r=>r.nsu}]);barChart('#targetChart',rs,[{name:'Total URLs',color:'#0f766e',get:r=>r.total},{name:'Target URLs',color:'#7652cb',get:r=>r.targetUrls}]);barChart('#prodChart',rs,[{name:'Productivity %',color:'#7652cb',get:r=>r.productivity}]);barChart('#utChart',rs,[{name:'UT %',color:'#0f766e',get:r=>r.ut}]);barChart('#exceptionChart',rs,[{name:'Exception Minutes',color:'#e59b32',get:r=>r.exception}]);barChart('#deficitChart',rs,[{name:'Target URL Deficit',color:'#c83b4d',get:r=>Math.max(0,r.deficitUrls)}]);barChart('#cumulativeProdChart',running,[{name:'Cumulative productivity',color:'#7652cb',get:r=>r.avgProd}]);barChart('#cumulativeUrlsChart',running,[{name:'Cumulative URLs',color:'#0f766e',get:r=>r.total}])}
  function drawPies(a){pieChart('#mixPie',[{name:'SU%',value:a.avgSu,color:'#0f766e'},{name:'NSU%',value:a.avgNsu,color:'#e59b32'}]);pieChart('#urlPie',[{name:'Completed URLs',value:a.completed,color:'#0f766e'},{name:'Remaining Target URLs',value:Math.max(0,a.target-a.completed),color:'#e59b32'}]);pieChart('#exceptionPie',[{name:'UT Exception',value:a.utEx,color:'#7652cb'},{name:'Productivity Exception',value:a.prodEx,color:'#c83b4d'}])}
  const dlWords=v=>String(v||'').split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);
  const dlCount=(words,list)=>Object.fromEntries(list.map(x=>[x,words.filter(w=>w.toLowerCase()===x.toLowerCase()).length]).filter(x=>x[1]));
  function dlSplit(text){const x=text.trim().replace(/\s+/g,' ');if(!x)return{one:'',two:'',valid:true};if(x.length>70)return{one:'',two:'',valid:false,reason:'Full DL exceeds 70 characters.'};if(x.length<=35)return{one:x,two:'',valid:true};let at=-1;for(let i=0;i<x.length;i++)if(x[i]===' '&&i<=35&&x.length-i-1<=35)at=i;return at<0?{one:'',two:'',valid:false,reason:'No word-boundary split can keep both DL1 and DL2 within 35 characters.'}:{one:x.slice(0,at),two:x.slice(at+1),valid:true}}
  function dlData(text){const token=[...text.matchAll(/[A-Za-z][A-Za-z'-]*/g)].map(x=>x[0]),protectedWords=new Set([...dlWords($('#dlNoChange').value),...dlWords($('#dlCapExceptions').value)].map(x=>x.toLowerCase()));let caps=[],mixed=[],upper=[],supers=[];const irregular=['best','worst','most','least'];token.forEach(w=>{const low=w.toLowerCase(),safe=protectedWords.has(low);if(!safe&&/^[A-Z]{2,}$/.test(w))upper.push(w);else if(!safe&&/[A-Z]/.test(w.slice(1)))mixed.push(w);else if(!safe&&((['a','an','the'].includes(low)&&w!==low)||(!['a','an','the'].includes(low)&&!(w[0]===w[0].toUpperCase()&&w.slice(1)===w.slice(1).toLowerCase()))))caps.push(w);if(/est$/i.test(w)||irregular.includes(low))supers.push(w)});const counts={};token.forEach(w=>counts[w.toLowerCase()]=(counts[w.toLowerCase()]||0)+1);return{token,caps,mixed,upper,superlatives:supers,protectedWords,repeated:Object.entries(counts).filter(x=>x[1]>1),spaces:[/^\s/.test(text)&&'leading space',/\s$/.test(text)&&'trailing space',...[...text.matchAll(/ {2,}/g)].map(x=>x[0].length+' spaces at character '+(x.index+1))].filter(Boolean),period:/\.$/.test(text)}}
  function renderAnalyzer(){const text=$('#dlText').value,d=dlData(text),keys=dlWords($('#dlKeywords').value),specific=dlWords($('#dlSpecific').value),split=dlSplit(text),foundK=dlCount(d.token,keys),foundS=dlCount(d.token,specific),join=a=>a.length?a.join(', '):'None',items=[['Character count',text.length+'/70'],['Capitalization errors',join(d.caps)],['Mixed capitalization errors',join(d.mixed)],['Uppercase words',join(d.upper)],['Superlatives',join(d.superlatives)],['Extra spacing',join(d.spaces)],['Repeated words',d.repeated.map(x=>x[0]+' ×'+x[1]).join(', ')||'None'],['Ending-period status',d.period?'PASS':'ERROR'],['Custom keywords found',Object.entries(foundK).map(x=>x[0]+' ×'+x[1]).join(', ')||'None'],['Specific words found',Object.entries(foundS).map(x=>x[0]+' ×'+x[1]).join(', ')||'None'],['DL1 character count',split.one.length],['DL2 character count',split.two.length],['Full DL character count',text.length]];const status=text.length<=65?'PASS · Recommended':text.length<=70?'WARNING · Within maximum limit':'ERROR · Above 70 characters';$('#dlCount').innerHTML='<b class="'+(text.length>70?'metric-bad':text.length>65?'metric-warn':'metric-good')+'">'+text.length+' / 70</b> · '+status;$('#dlSummary').innerHTML=items.map(x=>'<div class="check-row"><span>'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>').join('');const bad=new Set([...d.caps,...d.mixed,...d.upper].map(x=>x.toLowerCase()));$('#dlPreview').innerHTML=text?text.split(/([A-Za-z][A-Za-z'-]*)/).map(x=>{const low=x.toLowerCase(),c=[];if(keys.some(w=>w.toLowerCase()===low))c.push('hl-keyword');if(specific.some(w=>w.toLowerCase()===low))c.push('hl-specific');if(bad.has(low))c.push('hl-issue');return c.length?'<mark class="'+c.join(' ')+'">'+esc(x)+'</mark>':esc(x)}).join(''):'<span class="muted">Your unchanged DL preview appears here.</span>';const issues=[d.caps.length&&'Capitalization: '+join(d.caps),d.mixed.length&&'Mixed/internal capitals: '+join(d.mixed),d.upper.length&&'ALL-UPPERCASE: '+join(d.upper),d.spaces.length&&'Spacing: '+join(d.spaces),text&&!d.period&&'Ending period: ERROR — add a period.',!split.valid&&split.reason].filter(Boolean);$('#dlIssues').innerHTML=issues.map(x=>'<span class="issue">'+esc(x)+'</span>').join('');$('#dl1').textContent=split.one||'—';$('#dl2').textContent=split.two||'—';$('#dlOriginal').textContent=text||'—';$('#dl1Count').textContent=split.one.length+'/35';$('#dl2Count').textContent=split.two.length+'/35';$('#fullDlCount').textContent=text.length+'/70'}
  function initAnalyzer(){const map={keywords:'dlKeywords',specific:'dlSpecific',noChange:'dlNoChange',capExceptions:'dlCapExceptions'};Object.entries(map).forEach(x=>$('#'+x[1]).value=state.analyzerSettings[x[0]]||'');['dlText',...Object.values(map)].forEach(id=>$('#'+id).addEventListener('input',renderAnalyzer));$('#saveDlSettings').onclick=()=>{Object.entries(map).forEach(x=>state.analyzerSettings[x[0]]=$('#'+x[1]).value);persist();renderAnalyzer();toast('Analyzer settings saved')};$$('[data-copy]').forEach(b=>b.onclick=()=>{const v=b.dataset.copy==='original'?$('#dlText').value:$('#'+b.dataset.copy).textContent;if(v&&v!=='—'&&navigator.clipboard)navigator.clipboard.writeText(v).then(()=>toast('Copied'))});renderAnalyzer()}
  function exportCsv(){const rs=monthRecords(),a=aggregate(rs),heads=['Date','Days','SU','NSU','Total','SU%','NSU%','Target URLs','Deficit URLs','UT%','UT Deficit','Productivity @540','Productivity @472.5','Exception','UT Exception','UT Exception Hours','Productivity Exception','Productivity Exception Hours'],rows=rs.map(r=>[r.date,isWorkingDate(r.date)?'Working':'Off',r.su,r.nsu,r.total,r.suPct,r.nsuPct,r.targetUrls,r.deficitUrls,r.ut,r.utDeficit,r.prod540,r.productivity,r.exception,r.utException,r.utExceptionHours,r.prodException,r.prodExceptionHours]),csv=[['JAMES WORKFLOW'],['Selected month',$('#monthPicker').value],[],heads,...rows,[],['CUMULATIVE SUMMARY'],...summaryValues(a).map(x=>[x[0],x[1]])].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');download('james-workflow-'+$('#monthPicker').value+'.csv','text/csv;charset=utf-8',csv)}

  document.addEventListener('click',e=>{const b=e.target.closest('#nav button');if(b)showPage(b.dataset.page)});
  document.addEventListener('DOMContentLoaded',init);
})();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
